task_type: FARGATE
network_mode: awsvpc
cpu: 256
memory: 512

iam_policies:
  fargate_default_policy:
    action:
      - logs:GetLogEvents
    resource:
      - Fn::GetAtt: 
          - LogGroup
          - Arn

# scaling_policy:
#   min: 2
#   max: 4
#   up:
#     cooldown: 150
#     threshold: 70
#     evaluation_periods: 5
#     adjustment: 2
#   down:
#     cooldown: 600
#     threshold: 70
#     evaluation_periods: 5
#     adjustment: -1